### ISSUE TITLE
Question about statistically significant difference

### ISSUE THREAD

**Issue by zsw1456419654** [MungoMeng/Registration-NICE-Net#2]
Thank you for your excellent work in image registration and your available codes, but we want to know how to imple "the two-sided P<0.05  is considered to indicate a statistically significant difference" in your paper. Looking forward to receiving your reply！

**Comment by MungoMeng** [comment]
Please use the t.test function in R language to compare two sets of DSCs achieved by two different methods.

**Comment by zsw1456419654** [comment]
Thank you! Expect your future works!
